#!/usr/bin/env ruby

# Hide args from ps
$0 = $0

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "gphotos/app"

app = Gphotos::App.new(ARGV)
app.run
